Added documentation about the message schema to the about page.
LCOGT/hermes-frontend pull request #21
Opened 2023-03-07 18:55 UTC by cmccully

2023-03-07 20:54 UTC, jnation3406 requested changes
Just a few placement and key changes to line up with the schema

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'spectrum', Description: '<code>Spectrum</code> dict' },
this field is called `flux` in the schema right now

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'flux', Description: 'Array of floats: the flux values of the spectrum' },
this field is called `value` in the schema, since it appears in a table called `flux`

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'flux_type', Description: 'String: Type of flux in the reported spectrum; Choices: [Flambda, Fnu]' }
We don't have this field in our schema right now. Do we need it?

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
>  </style>
missing newline at end

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'catalog', Description: 'String: Reference astrometric catalog used, e.g. GAIA-DR2' },
there should be an `astrometry_catalog` and `photometry_catalog` field

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +            astrometry_items: [
Also missing `brightness`, `brightness_error`, `brightness_unit`, and `bandpass`

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'unit', Description: 'Brightness unit; Accepted values are [AB mag, Vega mag, Jsky, erg/s/cm^2/A]' },
Should be `brightness_unit`

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'limiting_brightness_unit', Description: 'String: Limiting Brightness unit; Accepted values are [AB mag, Vega mag, Jsky, erg/s/cm^2/A]', },
Add `limiting_brightness_error` as well.

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'catalog', Description: 'String: Reference photometric catalog used, e.g. SDSS' },
There is no `catalog` field in the schema for photometry. Should there be?

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'comments', Description: 'String: Type of spectrum; Choices: [Object, Host, Synthetic, Sky, Arcs]' },
I think you meant `spec_type` for this field

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'classification', Description: 'String: Classification of target. If submitting to TNS, classification must be a recognized TNS type.' },
It is actually required to be a TNS type no matter what - that is what the choices are derived from. I think `Other` is a valid option though, and the field likely isn't required to be set at all.

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'epoch', Description: 'String or Float: Epoch of the coordinates; Default is j2000. If a float is given, it is assumed to be Julian.' },
This is just a floatField now, so just say its a Julian epoch, default of 2000

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'epoch_of_perihelion', Description: 'Date/Time: Epoch of the Perihelion, typically for comets' }
This is a float field, so its probably assumed to be a Julian date I guess or whatever they use.

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +            items: [
You're missing one level here. The `event_id` through `astrometry` fields are within a `data` JSON field. The other fields are at the top level as described here.

2023-03-07 20:54 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'discovery', Description: 'bool: Is this target a new discovery?' },
The field is called `new_discovery`

2023-03-07 21:05 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'spectrum', Description: '<code>Spectrum</code> dict' },
I would advocate with not calling that table flux and calling it spectrum.

2023-03-07 21:06 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'flux', Description: 'Array of floats: the flux values of the spectrum' },
See above. It will make more sense for users with this set of keywords than having a value and wavelength field.

2023-03-07 21:06 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'flux_type', Description: 'String: Type of flux in the reported spectrum; Choices: [Flambda, Fnu]' }
We do unfortunately.

2023-03-07 21:07 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'catalog', Description: 'String: Reference astrometric catalog used, e.g. GAIA-DR2' },
I would advocate that we remove the photometry stuff from the astrometry section. We went to a lot of pains to separate targets into their own thing. I think we should be consistent.

2023-03-07 21:07 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'classification', Description: 'String: Classification of target. If submitting to TNS, classification must be a recognized TNS type.' },
Right, but at some level HERMES itself doesn't need to care. It only cares if submit to TNS is true.

2023-03-07 21:08 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'epoch_of_perihelion', Description: 'Date/Time: Epoch of the Perihelion, typically for comets' }
Yeah. This should be more flexible.

2023-03-07 21:09 UTC, cmccully commented on src/views/AboutHermes.vue
> +            items: [
Why is that? Does it need to have a data section? That seems less useful now.

2023-03-07 21:11 UTC, cmccully commented on src/views/AboutHermes.vue
> +            astrometry_items: [
See above.

2023-03-07 21:11 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'catalog', Description: 'String: Reference photometric catalog used, e.g. SDSS' },
I would advocate moving the photometry catalog from the astrometry section to the photometry section where it is more relevant.

2023-03-07 21:12 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'comments', Description: 'String: Type of spectrum; Choices: [Object, Host, Synthetic, Sky, Arcs]' },
I did mean that...

2023-03-07 21:21 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'catalog', Description: 'String: Reference astrometric catalog used, e.g. GAIA-DR2' },
@jchate6 What do you think of the above since you crafted this section

2023-03-07 21:22 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'flux', Description: 'Array of floats: the flux values of the spectrum' },
Okay, I'm fine with that. Also noticed that you have this as a dict with lists of several fields. Instead I have it as a list of dicts, which I think is a bit easier to represent.

2023-03-07 21:24 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'epoch_of_perihelion', Description: 'Date/Time: Epoch of the Perihelion, typically for comets' }
Are you saying we should make it a char field so that it can accept a datetime or float? Or are you saying a float field is fine?

2023-03-07 21:26 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +            items: [
yes. This makes the way the message is submitted is the way it is stored. I would like to not do magic on either end to give the user and have them submit other than what is being stored. The top level fields like message_text/authors/submitter are all explicit DB fields at the top level, but all the message schema stuff is within a single `data` JSON field.

2023-03-07 21:28 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'flux', Description: 'Array of floats: the flux values of the spectrum' },
I think for the message itself it should be a dict of lists. Otherwise you have a lot of redundant copies of the keys. Given that we have 1 MB message size limit, we shouldn't pollute it too much with redundant text. In the DB it makes perfect sense to represent each flux measurement as a row in the table, but transmitting the message is better in this format.

2023-03-07 21:29 UTC, cmccully commented on src/views/AboutHermes.vue
> +            items: [
I would advocate against having the extra data field in either representation. It only adds a layer of nesting without adding any new information.

2023-03-07 21:31 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'flux', Description: 'Array of floats: the flux values of the spectrum' },
Where is this 1MB message size limit coming from?? I guess I would not really worry about duplicating keys unless we are submitting messages with 10k+ fluxes per spectroscopy datum routinely. I was under the impression it would be on the order of 1-10, i.e. much smaller numbers of fluxes per spectroscopy datum usually...

2023-03-07 21:32 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'epoch_of_perihelion', Description: 'Date/Time: Epoch of the Perihelion, typically for comets' }
I think it would make more sense as a char field like our other date times (and in fact use the same validation logic).

2023-03-07 21:34 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'flux', Description: 'Array of floats: the flux values of the spectrum' },
Unfortunately it does happen. 10k pixels is not actually that much. FLOYDS is low resolution and has ~6000 flux values per spectrum. The 1MB limit is from kafka.

2023-03-07 21:34 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'flux', Description: 'Array of floats: the flux values of the spectrum' },
There is something to be said for user readability as well.

2023-03-07 21:37 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'flux', Description: 'Array of floats: the flux values of the spectrum' },
Also, I just tested a message with 50 fluxes and 20 targets, and it is 6.5Kb... I think the UI will break before you can compose a message that is 1MB

2023-03-07 21:50 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'epoch_of_perihelion', Description: 'Date/Time: Epoch of the Perihelion, typically for comets' }
Okay, I've converted all epochs to strings, and am doing the same validation for float/dateparser on all of them now.

2023-03-08 18:20 UTC, cmccully commented
![Screenshot 2023-03-08 at 1 17 39 PM](https://user-images.githubusercontent.com/5331996/223798172-ccaa50b8-71f4-4611-9135-dfbbebd38dcc.png)
![Screenshot 2023-03-08 at 1 17 55 PM](https://user-images.githubusercontent.com/5331996/223798167-dd43967f-c13f-4c5e-b961-f653cccc8cde.png)
![Screenshot 2023-03-08 at 1 18 08 PM](https://user-images.githubusercontent.com/5331996/223798163-6bfa8b40-0a17-4b15-90b2-0c299b251bfc.png)
![Screenshot 2023-03-08 at 1 18 18 PM](https://user-images.githubusercontent.com/5331996/223798156-4d5e74c7-1f2e-4c64-8a8b-add50c079060.png)
![Screenshot 2023-03-08 at 1 18 35 PM](https://user-images.githubusercontent.com/5331996/223798150-6ededb6f-1f0c-4031-b107-72481f3c080e.png)
![Screenshot 2023-03-08 at 1 18 54 PM](https://user-images.githubusercontent.com/5331996/223798137-9c67029c-3d95-4f2e-8f10-9ff2e31eb01a.png)

2023-03-09 18:58 UTC, jchate6 commented on src/views/AboutHermes.vue
> +                { Field: 'catalog', Description: 'String: Reference photometric catalog used, e.g. SDSS' },
You need both.

2023-03-09 19:00 UTC, jchate6 commented on src/views/AboutHermes.vue
> +            astrometry_items: [
Again, you need both. Unless we incorporate a way to tie an astrometric Data point to a specific photometric datapoint, we need people submitting astrometry to have the option to include how bright the target was during that specific observation.

The validation makes these different fields.

2023-03-09 19:03 UTC, jchate6 commented on src/views/AboutHermes.vue
> +                { Field: 'catalog', Description: 'String: Reference astrometric catalog used, e.g. GAIA-DR2' },
Removing the optional photometry fields from the astrometric submission doesn't work. The fields are optional.

The reason separating Targets works is because we can link the target to each datum. We can't link one datum to another.

2023-03-09 19:05 UTC, jchate6 commented on src/views/AboutHermes.vue
> +                { Field: 'wavelegnth_unit', Description: 'String: Units of the wavelength values; Choices: [A, nm, Hz, GHz, THz]' },
I believe `um` is also a valid option here.

2023-03-09 19:12 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'catalog', Description: 'String: Reference astrometric catalog used, e.g. GAIA-DR2' },
I don't understand. Isn't obstime enough of reference to the other datum? This feels artificial.

2023-03-09 19:27 UTC, jchate6 commented on src/views/AboutHermes.vue
> +                { Field: 'catalog', Description: 'String: Reference astrometric catalog used, e.g. GAIA-DR2' },
So, no, obstime does not explicitly link two datums. 

Also, from a user perspective (speaking as someone who has actively done astrometry of both stars and asteroids for almost 15 years) one would not expect to have to fill out a completely different photometry table in order to record or report the (usually pretty bad) photometric estimates that comes for free with an astrometric measurement. The intuitive thing here is just to record the magnitude alongside the positions.

It doesn't feel any more artificial to include a few photometric fields in an astrometry table than to repeat the telescope/instrument fields. Brightness information is part of what you get from an astrometric measurement, and it is typically used differently than dedicated photometry data.

2023-03-09 20:08 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'wavelegnth_unit', Description: 'String: Units of the wavelength values; Choices: [A, nm, Hz, GHz, THz]' },
oh yes I didn't notice this. I currently have all the distance units, but none of the frequency ones. Do we want to support he frequency units too?

2023-03-09 20:23 UTC, jchate6 commented on src/views/AboutHermes.vue
> +                { Field: 'catalog', Description: 'String: Reference astrometric catalog used, e.g. GAIA-DR2' },
For the record, If you want to remove any brightness measurements from this table I think that's fine. It's just not following the principle of least surprise for the average use case I'm familiar with. Realistically, getting distracted by astrometry tables when O4 very much needs to be the focus is probably not in anyone's best interest.

2023-03-09 20:37 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +            items: [
I think in this case specifically, we really should keep it as-is, unless you are suggesting with create DB fields for each section rather than a catch-all `data` field? If thats the case, do you think non-hermes messages should have all their parsed data go into the `extra_data` JSONField instead of the `data` field they all use now?

2023-03-09 20:40 UTC, cmccully commented on src/views/AboutHermes.vue
> +            items: [
I was thinking of having the photometry, etc as json fields in the db. The non hermes message is an interesting question. I will need to think about it a little bit.

2023-03-21 22:10 UTC, jnation3406 commented on src/views/AboutHermes.vue
> +                { Field: 'url', Description: 'String, required: URL to the reference e.g. doi.org/mydoi' }
either source + citation or url is required, so the required relationship is a bit more complex then described here.

2023-03-22 18:43 UTC, cmccully commented on src/views/AboutHermes.vue
> +                { Field: 'url', Description: 'String, required: URL to the reference e.g. doi.org/mydoi' }
I think they should all be required here. At least for V1. If someone cites source: ApJ, citation McCully et al. 2022 and doesn't give a URL things will get confusing. I think we need user feedback on what values should actually go into the citation field.

2023-03-22 18:44 UTC, cmccully commented on src/views/AboutHermes.vue
> +                                <b-table striped hover :items="items">
I tried this and ran into issues with a bcard inside a bcard. I can try again, but this could be something that @jchate6 could also look at.

2023-03-22 18:45 UTC, cmccully commented on src/views/AboutHermes.vue
> +            items: [
I think I've come to the conclusion that all non hermes messages json data should go into the extra_data field. That's kind of the point of hermes to provide the structure so if they don't use it, we just put everything into a dict.

2023-03-24 16:57 UTC, jchate6 commented on src/views/AboutHermes.vue
> +                { Field: 'url', Description: 'String, required: URL to the reference e.g. doi.org/mydoi' }
There may not be a URL for certain citations.

2023-03-27 22:52 UTC, merged